[versions]
indra = "2.1.1"
checkstyle = "10.3.1"
guava = "31.1-jre"
slf4j = "1.7.36"

[libraries]
# utilities
jetbrains-annotations = "org.jetbrains:annotations:23.0.0"
guava = { module = "com.google.guava:guava", version.ref = "guava" }

# logger
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-checkstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-publishing-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
